### PR TITLE
Change autoload type from psr-0 to psr-4

### PR DESCRIPTION
**Pull request by niel**
Fix for autoloading problems with Composer.

### CODE REVIEW

**Comment by niel** [comment]
Do you need to update Packagist after this merge? So far after several tries Composer is still fetching the old version with commit #356ad3

**Comment by JPinkney** [comment]
I just got an email saying the composer.json became invalid thats why it didn't update. I'm looking into right now

**Comment by JPinkney** [comment]
I believe i've fixed it. I guess you needed trailing slashes after JPinkney in psr-4 otherwise it will throw invalid composer file

**Comment by niel** [comment]
Bugger, you're right.

**Pull request merged**
